package Drools

import com.sample.Local;

rule "If speed is required, we boot the fastest VM"

    when
        local : Local( local.getLoad() < 40 )
    then
       	System.out.println("Other processes (with low priority) can be started.");

end

rule "If accurate logging is required, we boot the appropriate VM"

    when
        local : Local( local.getLoad() > 40 && local.getLoad() < 80 )
    then
       	System.out.println("Other processes (with low priority) can be started.");

end

rule "If the local server is to busy, everything has to be forwarded to the cloud."

    when
        local : Local( local.getLoad() > 80 )
    then
       	System.out.println("send to cloud Drool");

end
